services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    image: migration
    build:
      context: .
      dockerfile: migration.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy

  # TODO: add traefik
  app:
    image: wildlog
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
    labels:
      - "traefik.enable=true"
    networks:
      - proxy
      - default
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

# studio:
#   image: ghcr.io/drizzle-team/gateway:latest
#   restart: unless-stopped
#   ports:
#     - "4983:4983"
#   environment:
#     MASTERPASS: masterpass
#   volumes:
#     - drizzle-gateway:/app

volumes:
  postgres_data:
# drizzle-gateway:

networks:
  proxy:
    name: proxy
